### ISSUE TITLE
Pyregion should use distortion-aware WCS functions for coordinate transformations

### ISSUE THREAD

**Issue by mcara** [astropy/pyregion#35]
Currently, `pyregion` uses WCS functions that do not take into account distortion corrections: `wcs.wcs_world2pix()` and `wcs.wcs_pix2world()`. However, distortions for most HST instruments are significant and should be taken into account. This could be done  by switching to  `wcs.all_world2pix()` and `wcs.all_pix2world()` - really a very simple change to the code.

While at this moment I cannot recommend this change until issues in https://github.com/astropy/astropy/issues/1977, https://github.com/scipy/scipy/issues/3227, https://github.com/astropy/astropy/pull/2294 are solved. I have submitted a PR that fixes these issues in `all_world2pix()` and provides performance improvements https://github.com/astropy/astropy/pull/2373 but it is not yet merged.

I will post here when it is safe to do this transition.

NOTE: for images that do not have distortions  `wcs.all_world2pix()` and `wcs.all_pix2world()` are similar to their -non-distortion-aware analogs `wcs.wcs_world2pix()` and `wcs.wcs_pix2world()`.

**Comment by cdeil** [comment]
@mcara - Thanks for filing this issue.

All of the issues you linked to are now closed or merged.

Maybe, as a start, @mcara , you could post a test case example here, or contribute it directly as a test via a pull request?

Such a concrete example could be useful, so that everyone can run it through DS9 and pyregion and then participate in the discussion whether the change you're proposing should be made.

**Comment by mcara** [comment]
@cdeil Please review my PR https://github.com/astropy/pyregion/pull/97
